version: '3.8'

services:
  web:
    environment:
      - DB_HOST=db
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=predictions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
